[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "BiciMad"
version = "0.0.1"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
exclude = ["tests/*", "data/*"]